substitutions:
  esphome_name: e-ink-co2-monitor
  battery_voltage_min: "3.5"
  battery_voltage_max: "4.2"

esphome:
  name: "${esphome_name}"

esp32:
  board: featheresp32

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  fast_connect: true
  power_save_mode: HIGH
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Deep sleep configuration
deep_sleep:
  id: deep_sleep_control
  run_duration: 10s
  sleep_duration: 30min

# Time synchronization
time:
  - platform: homeassistant
    id: esptime
    on_time:
      # Sleep at 8pm, wake at 5am
      - hours: 20
        then:
          - deep_sleep.enter:
              id: deep_sleep_control
              until: "05:00:00"
              time_id: esptime

# Sensors
sensor:
  # Home Assistant sensors
  - platform: homeassistant
    id: sensor_co2
    entity_id: sensor.my_carbon_dioxide_sensor
    accuracy_decimals: 0
    on_value:
      then:
        - component.update: display_eink

  - platform: homeassistant
    id: sensor_temperature
    entity_id: sensor.my_temperature_sensor
    accuracy_decimals: 0

  - platform: homeassistant
    id: sensor_humidity
    entity_id: sensor.my_humidity_sensor  
    accuracy_decimals: 0

  # Battery monitoring
  - platform: adc
    id: sensor_battery_voltage
    name: "${esphome_name} Battery Voltage"
    update_interval: 5s
    attenuation: 11dB
    icon: "mdi:battery-charging"
    device_class: "voltage"
    entity_category: "diagnostic"
    pin: 35
    accuracy_decimals: 2
    filters:
      - multiply: 2

  - platform: copy
    id: battery_level
    name: "${esphome_name} Battery Level"
    device_class: "battery"
    entity_category: "diagnostic"
    unit_of_measurement: "%"
    source_id: sensor_battery_voltage
    accuracy_decimals: 0
    filters:
      - lambda: return min(((x - ${battery_voltage_min}) / (${battery_voltage_max} - ${battery_voltage_min})) * 100, 100.0);

# SPI configuration for display
spi:
  clk_pin: 18
  mosi_pin: 23

# E-ink display
display:
  - platform: waveshare_epaper
    id: display_eink
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 2.13in-ttgo-b74
    update_interval: never
    full_update_every: 96  # Full update once daily (at 15min intervals)
    rotation: 270
    lambda: |-
      it.clear();
      
      // Check battery level - show low battery warning if needed
      if (id(sensor_battery_voltage).state <= ${battery_voltage_min}) {
        // Center the battery icon
        int start_x = (it.get_width() - 122) / 2;
        int start_y = (it.get_height() - 50) / 2;
        
        // Draw battery outline
        it.rectangle(start_x, start_y, 100, 50);
        it.filled_rectangle(start_x, start_y, 5, 50);
        
        // Draw battery terminal
        it.rectangle(start_x + 102, start_y + 15, 10, 20);
      } else {
        // Normal display - show sensor data
        it.filled_rectangle(20, 25, 5, 70, COLOR_ON);
        it.printf(35, 25, id(font_m), COLOR_ON, TextAlign::LEFT, "CO2");
        it.printf(35, 50, id(font_l), COLOR_ON, TextAlign::LEFT, "%.0f ppm", id(sensor_co2).state);
        it.printf(it.get_width() - 10, 10, id(font_m), COLOR_ON, TextAlign::RIGHT, "%.1f°C %.0f%%", 
                 id(sensor_temperature).state, id(sensor_humidity).state);
      }

# Fonts
font:
  - file: "gfonts://Roboto"
    id: font_s
    size: 15
    
  - file: "gfonts://Roboto"
    id: font_m
    size: 20
    
  - file: "gfonts://Roboto@bold"
    id: font_l
    size: 40